better detection of if BASE_TMP_DIR is good for an upperfs, don't hardcode detection of just overlayfs, it requires root though, to create the workdir

diff --git a/checkinstall b/checkinstall
--- a/checkinstall
+++ b/checkinstall
@@ -492,7 +492,7 @@ function copy_dir_hierarchy {
 }
 
 # TODO better detection, right now, it tests using the path in a namespace
-function checkcanoverlay
+function checkcanoverlayaslower
 {
   #Use a user namespace, only if the user isn't the root user
   if [[ $UID == 0 ]]
@@ -501,6 +501,27 @@ function checkcanoverlay
   else
     unshare -rm mount -t overlay overlay -o lowerdir="$1:$1"  /tmp/ &>/dev/null
   fi
+  overlaytestresult=$?
+  if [[ $overlaytestresult == 0 ]]
+  then
+    return 0
+  else
+    return 1
+  fi
+}
+
+# TODO better detection, right now, it tests using the path in a namespace
+function checkcanoverlayasupper
+{
+  #Use a user namespace, only if the user isn't the root user
+  if [[ $UID != 0 ]]
+  then
+    >&2 echo "Warning: Not running as root, cannot detect if $1 is able to be used as the upperdir of an overlayfs"
+    return 0
+  fi
+  mkdir -p "$1/.ovlprobeworkdir"
+  unshare -m mount -t overlay overlay -o lowerdir=/,upperdir="$1",workdir="$1/.ovlprobeworkdir"  /tmp/ &>/dev/null
+  rmdir "$1/.ovlprobeworkdir"
   overlaytestresult=$?
   if [[ $overlaytestresult == 0 ]]
   then
@@ -533,13 +554,7 @@ function getmountmap
     CHROOTPATH=/
   fi
 
-  #Overlayfs cant be on the upperdir of overlayfs, if /var/tmp is overlayfs, create ramdisk that will use 50% of memory maximum
-  TRANLFSTYPE=$(df -T "$BASE_TMP_DIR" | tail -1 | awk '{print $2}')
-  if [[ $TRANLFSTYPE == "overlay" ]]
-  then
-    >&2 echog "$BASE_TMP_DIR cannot be an overlayfs."
-    return 1
-  fi
+
 
   FSES=$(findmnt -vUPno MAJ:MIN,FSROOT,TARGET,ID  | sed -e "s|$CHROOTPATH|/|g" -e "s|//|/|g" -e "s|^MAJ:MIN=|MAJ_MIN=|g" | sort -k4,4n --stable)
 
@@ -557,7 +572,16 @@ function getmountmap
 
   FILE_IS_BIND_MOUNTED=0
   UNSUPPORTED_LOWERDIR_FS=0
+  UNSUPPORTED_UPPERDIR_FS=0
 
+  #Overlayfs cant be on the upperdir of overlayfs, if /var/tmp is overlayfs, fallback
+  checkcanoverlayasupper "$BASE_TMP_DIR"
+  filesystemcanoverlayupper=$?
+  if [[ $filesystemcanoverlayupper != 0 ]]
+  then
+    >&2 echog "$BASE_TMP_DIR is not supported as the upperdir for overlayfs."
+    UNSUPPORTED_UPPERDIR_FS=1
+  fi
 
   unset DONE1FSES
   IFS=$'\n'
@@ -638,9 +662,9 @@ function getmountmap
         if [[ $TARGETEXCLUDED == 0 ]]
         then
           #Detect if the filesystem can support overlayfs
-          checkcanoverlay "$SEARCH2TARGET"
-          filesystemcanoverlay=$?
-          if [[ $filesystemcanoverlay != 0 ]]
+          checkcanoverlayaslower "$SEARCH2TARGET"
+          filesystemcanoverlaylower=$?
+          if [[ $filesystemcanoverlaylower != 0 ]]
           then
             >&2 echog "$SEARCH2TARGET is not supported by overlayfs"
             UNSUPPORTED_LOWERDIR_FS=1
@@ -656,7 +680,7 @@ function getmountmap
     fi
   done
 
-  if [[ $UNSUPPORTED_LOWERDIR_FS == 1 || $FILE_IS_BIND_MOUNTED == 1 ]]
+  if [[ $UNSUPPORTED_LOWERDIR_FS == 1 || $UNSUPPORTED_UPPERDIR_FS == 1 || $FILE_IS_BIND_MOUNTED == 1 ]]
   then
     return 1
   else
