error spelling fixes

diff --git a/checkinstall b/checkinstall
--- a/checkinstall
+++ b/checkinstall
@@ -684,7 +684,7 @@ function createtraslationmounts
         MOUNTFAILCOUNT+=$MOUNTRESULT
         if [[ $MOUNTRESULT != 0 ]]
         then
-          >&2 echo "Failed to bin in non unioned $MOUNTDEST"
+          >&2 echo "Failed to bind in non unioned $MOUNTDEST"
         fi
       fi
     else
@@ -720,7 +720,7 @@ function createtraslationmounts
   MOUNTFAILCOUNT+=$MOUNTRESULT
   if [[ $MOUNTRESULT != 0 ]]
   then
-    >&2 echo "Failed to piviot_root"
+    >&2 echo "Failed to pivot_root"
   fi
 
   if [[ $MOUNTFAILCOUNT == 0 ]]
