echog is not in installscript.sh, and createtraslationmounts is called by installscript.sh

diff --git a/checkinstall b/checkinstall
--- a/checkinstall
+++ b/checkinstall
@@ -691,7 +691,7 @@ function createtraslationmounts
         MOUNTFAILCOUNT+=$MOUNTRESULT
         if [[ $MOUNTRESULT != 0 ]]
         then
-          >&2 echog "Failed to union mount $MOUNTDEST"
+          >&2 echo "Failed to union mount $MOUNTDEST"
         fi
       else
         mount --bind $MOUNTDEST "${TMP_DIR}/workdir/$MOUNTDEST"
@@ -699,7 +699,7 @@ function createtraslationmounts
         MOUNTFAILCOUNT+=$MOUNTRESULT
         if [[ $MOUNTRESULT != 0 ]]
         then
-          >&2 echog "Failed to bind in non unioned $MOUNTDEST"
+          >&2 echo "Failed to bind in non unioned $MOUNTDEST"
         fi
       fi
     else
@@ -712,17 +712,17 @@ function createtraslationmounts
         MOUNTFAILCOUNT+=$MOUNTRESULT
         if [[ $MOUNTRESULT != 0 ]]
         then
-          >&2 echog "Failed bind mount real $MOUNTSOURCE to $MOUNTDEST"
+          >&2 echo "Failed bind mount real $MOUNTSOURCE to $MOUNTDEST"
         fi
         mount --bind "${TMP_DIR}/workdir/$MOUNTSOURCE" "${TMP_DIR}/workdir/$MOUNTDEST"
         MOUNTRESULT=$?
         MOUNTFAILCOUNT+=$MOUNTRESULT
         if [[ $MOUNTRESULT != 0 ]]
         then
-          >&2 echog "Failed bind mount translation $MOUNTSOURCE to $MOUNTDEST"
+          >&2 echo "Failed bind mount translation $MOUNTSOURCE to $MOUNTDEST"
         fi
       else
-        >&2 echog "$MOUNTSOURCE does not exist"
+        >&2 echo "$MOUNTSOURCE does not exist"
         MOUNTFAILCOUNT+=1
       fi
     fi
@@ -735,7 +735,7 @@ function createtraslationmounts
   MOUNTFAILCOUNT+=$MOUNTRESULT
   if [[ $MOUNTRESULT != 0 ]]
   then
-    >&2 echog "Failed to pivot_root"
+    >&2 echo "Failed to pivot_root"
   fi
 
   if [[ $MOUNTFAILCOUNT == 0 ]]
